import type { Metadata } from 'next';
import Link from 'next/link';
import { Scale, ArrowLeft } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Terms of Service | EU AI Act Compliance Checker',
  description:
    'Terms of Service for EU AI Pass — the EU AI Act Compliance Checker. Informational use only, not legal advice.',
};

export default function TermsOfServicePage() {
  const lastUpdated = '26 September 2026';

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-[#070b14] text-slate-900 dark:text-slate-100">
      {/* Header */}
      <header className="border-b border-slate-200/80 dark:border-slate-800/80 bg-white/80 dark:bg-[#090e1a]/80 backdrop-blur-md">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 h-16 flex items-center justify-between">
          <Link
            href="/"
            className="flex items-center gap-2 text-sm font-medium text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to Compliance Checker
          </Link>
          <div className="flex items-center gap-2">
            <Scale className="w-5 h-5 text-blue-600" />
            <span className="font-bold text-sm text-slate-900 dark:text-white">EU AI Pass</span>
          </div>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-4 sm:px-6 py-12 sm:py-16">
        <div className="space-y-8">
          {/* Title */}
          <div className="space-y-3">
            <h1 className="text-3xl sm:text-4xl font-black text-slate-900 dark:text-white tracking-tight">
              Terms of Service
            </h1>
            <p className="text-sm text-slate-500 dark:text-slate-400">
              Last updated: {lastUpdated} · Effective immediately
            </p>
            <p className="text-base text-slate-700 dark:text-slate-300 leading-relaxed">
              Please read these Terms of Service (&ldquo;Terms&rdquo;) carefully before using{' '}
              <strong>EU AI Pass</strong> at{' '}
              <a
                href="https://euaipass.com"
                className="text-blue-600 dark:text-blue-400 hover:underline"
              >
                euaipass.com
              </a>{' '}
              (the &ldquo;Service&rdquo;). By accessing or using the Service, you agree to be bound
              by these Terms.
            </p>
          </div>

          <hr className="border-slate-200 dark:border-slate-800" />

          {/* Section 1 */}
          <Section title="1. Description of Service">
            <p>
              EU AI Pass provides an automated AI risk tier classification tool that analyses
              AI system descriptions against Regulation (EU) 2024/1689 (the EU AI Act). The Service
              offers:
            </p>
            <ul className="list-disc list-inside space-y-1 mt-2">
              <li>A free risk tier badge (Prohibited / High Risk / Limited Risk / Minimal Risk)</li>
              <li>
                A paid one-time PDF audit report ($29 USD) containing detailed statutory obligations,
                regulatory citations, and a prioritised remediation checklist
              </li>
              <li>An optional permanent account to store and access your purchased reports</li>
            </ul>
          </Section>

          {/* Section 2 — NOT Legal Advice */}
          <Section title="2. Important Disclaimer: Not Legal Advice">
            <div className="bg-amber-50 dark:bg-amber-950/30 border border-amber-200 dark:border-amber-900/50 rounded-xl p-4 space-y-2">
              <p className="font-bold text-amber-900 dark:text-amber-200 text-sm">
                ⚠ Informational Purposes Only
              </p>
              <p className="text-sm text-amber-900/90 dark:text-amber-200/80 leading-relaxed">
                The Service and all outputs — including risk tier classifications, statutory
                obligation summaries, PDF reports, and any content generated by the tool — are{' '}
                <strong>provided for informational purposes only and do not constitute legal
                advice, legal counsel, or official conformity certification</strong> under
                Regulation (EU) 2024/1689 or any other applicable law.
              </p>
              <p className="text-sm text-amber-900/90 dark:text-amber-200/80 leading-relaxed">
                No attorney-client relationship is formed by your use of this Service. For any
                binding legal determination regarding your AI system&apos;s compliance status,
                you must consult qualified legal counsel and/or the relevant notified bodies or
                competent national authorities in your jurisdiction.
              </p>
            </div>
          </Section>

          {/* Section 3 — Eligibility */}
          <Section title="3. Eligibility & Acceptance">
            <p>
              You must be at least 18 years of age and have the legal authority to enter into a
              binding contract to use the Service. By using the Service, you represent and warrant
              that you meet these requirements.
            </p>
          </Section>

          {/* Section 4 — Payment */}
          <Section title="4. Payments & Refund Policy">
            <SubSection title="4a. Pricing">
              <p>
                The full PDF compliance report is available for a one-time fee of{' '}
                <strong>$29 USD</strong> (or the local currency equivalent as displayed at checkout).
                Prices are exclusive of any applicable taxes.
              </p>
            </SubSection>

            <SubSection title="4b. Payment Processing">
              <p>
                All payments are processed securely by <strong>Stripe, Inc.</strong> We do not store
                your credit card information. By completing a purchase, you agree to{' '}
                <a
                  href="https://stripe.com/legal"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-blue-600 dark:text-blue-400 hover:underline"
                >
                  Stripe&apos;s Terms of Service
                </a>
                .
              </p>
            </SubSection>

            <SubSection title="4c. Refund Policy">
              <p>
                Due to the immediate digital delivery nature of the product (PDF report delivered
                by email upon payment confirmation), <strong>all sales are final</strong>.
              </p>
              <p className="mt-2">
                However, we offer a <strong>24-hour satisfaction guarantee</strong>. If your PDF
                report was not delivered within 24 hours of payment, or if you experienced a
                technical error that prevented delivery, contact us at{' '}
                <a
                  href="mailto:support@euaipass.com"
                  className="text-blue-600 dark:text-blue-400 hover:underline"
                >
                  support@euaipass.com
                </a>{' '}
                within 72 hours of purchase and we will issue a full refund.
              </p>
            </SubSection>

            <SubSection title="4d. Taxes">
              <p>
                You are responsible for any applicable sales tax, VAT, GST, or similar taxes in your
                jurisdiction. For EU business customers, VAT reverse charge may apply. Your Stripe
                receipt will reflect applicable taxes.
              </p>
            </SubSection>
          </Section>

          {/* Section 5 — Acceptable Use */}
          <Section title="5. Acceptable Use">
            <p>You agree not to use the Service to:</p>
            <ul className="list-disc list-inside space-y-1 mt-2">
              <li>Submit false, misleading, or fabricated AI system descriptions</li>
              <li>Attempt to reverse-engineer, scrape, or systematically extract data from the Service</li>
              <li>
                Present the PDF report output as an official legal opinion, conformity assessment, or
                CE marking certificate
              </li>
              <li>Resell or redistribute PDF reports without our written consent</li>
              <li>
                Use the Service in violation of any applicable law or Regulation (EU) 2024/1689
              </li>
              <li>Interfere with or disrupt the Service infrastructure or servers</li>
            </ul>
          </Section>

          {/* Section 6 — Intellectual Property */}
          <Section title="6. Intellectual Property">
            <p>
              All content, software, trademarks, and intellectual property on the Service are owned
              by EU AI Pass. Upon purchase, you receive a <strong>non-exclusive, non-transferable
              personal licence</strong> to use the PDF report for your internal compliance
              assessment purposes only.
            </p>
          </Section>

          {/* Section 7 — Limitation of Liability */}
          <Section title="7. Limitation of Liability">
            <p>
              To the maximum extent permitted by applicable law, EU AI Pass and its operators shall
              not be liable for:
            </p>
            <ul className="list-disc list-inside space-y-1 mt-2">
              <li>Any regulatory fines, penalties, or enforcement actions taken against you</li>
              <li>Any business losses arising from reliance on the Service output</li>
              <li>
                Any indirect, incidental, special, consequential, or punitive damages arising from
                your use of or inability to use the Service
              </li>
            </ul>
            <p className="mt-3">
              Our total liability to you for any claim arising from the Service shall not exceed the
              amount you paid for the specific transaction giving rise to the claim.
            </p>
          </Section>

          {/* Section 8 — Disclaimers */}
          <Section title="8. Disclaimer of Warranties">
            <p>
              The Service is provided <strong>&ldquo;as is&rdquo;</strong> and{' '}
              <strong>&ldquo;as available&rdquo;</strong> without any warranties of any kind, either
              express or implied. We do not warrant that:
            </p>
            <ul className="list-disc list-inside space-y-1 mt-2">
              <li>The Service will be uninterrupted, error-free, or secure</li>
              <li>The classification results will be accurate, complete, or current</li>
              <li>
                The output will satisfy any specific legal or regulatory requirement in your
                jurisdiction
              </li>
            </ul>
            <p className="mt-2 text-xs text-slate-500 dark:text-slate-400">
              The EU AI Act Regulation (EU) 2024/1689 is subject to ongoing guidance and
              interpretation by the European AI Office and national competent authorities. The
              Service reflects our best understanding of the Act at the time of its last update.
            </p>
          </Section>

          {/* Section 9 — Privacy */}
          <Section title="9. Privacy">
            <p>
              Your use of the Service is also governed by our{' '}
              <Link href="/privacy" className="text-blue-600 dark:text-blue-400 hover:underline">
                Privacy Policy
              </Link>
              , which is incorporated into these Terms by reference.
            </p>
          </Section>

          {/* Section 10 — Termination */}
          <Section title="10. Termination">
            <p>
              We reserve the right to terminate or suspend your access to the Service at any time,
              with or without notice, if we reasonably believe you have violated these Terms.
            </p>
          </Section>

          {/* Section 11 — Governing Law */}
          <Section title="11. Governing Law & Dispute Resolution">
            <p>
              These Terms are governed by and construed in accordance with applicable law. Any
              disputes arising under these Terms shall first be submitted to mediation before
              pursuing litigation. For EU consumers, the European Commission&apos;s Online Dispute
              Resolution platform is available at{' '}
              <a
                href="https://ec.europa.eu/consumers/odr"
                target="_blank"
                rel="noopener noreferrer"
                className="text-blue-600 dark:text-blue-400 hover:underline"
              >
                ec.europa.eu/consumers/odr
              </a>
              .
            </p>
          </Section>

          {/* Section 12 — Changes */}
          <Section title="12. Changes to These Terms">
            <p>
              We may update these Terms from time to time. The &ldquo;Last updated&rdquo; date at
              the top of this page indicates the date of the most recent revision. Continued use of
              the Service after changes are posted constitutes acceptance of the updated Terms.
            </p>
          </Section>

          {/* Contact */}
          <div className="bg-blue-50 dark:bg-blue-950/30 border border-blue-200 dark:border-blue-900/50 rounded-xl p-5">
            <p className="font-semibold text-blue-900 dark:text-blue-200 text-sm mb-1">
              Questions?
            </p>
            <p className="text-sm text-blue-800 dark:text-blue-300">
              Contact us at{' '}
              <a
                href="mailto:support@euaipass.com"
                className="font-medium hover:underline"
              >
                support@euaipass.com
              </a>
              .
            </p>
          </div>

          {/* Back link */}
          <div className="pt-4">
            <Link
              href="/"
              className="inline-flex items-center gap-2 text-sm font-medium text-blue-600 dark:text-blue-400 hover:underline"
            >
              <ArrowLeft className="w-4 h-4" />
              Return to EU AI Act Compliance Checker
            </Link>
          </div>
        </div>
      </main>

      <footer className="border-t border-slate-200/80 dark:border-slate-800/80 py-6 mt-16 text-center text-xs text-slate-400">
        <div className="max-w-4xl mx-auto px-4 space-x-4">
          <Link href="/privacy" className="hover:text-slate-600 dark:hover:text-slate-200 transition-colors">Privacy Policy</Link>
          <Link href="/terms" className="hover:text-slate-600 dark:hover:text-slate-200 transition-colors">Terms of Service</Link>
          <span>© {new Date().getFullYear()} EU AI Pass</span>
        </div>
      </footer>
    </div>
  );
}

// ── Sub-components ──────────────────────────────────────────────────────────

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-3">
      <h2 className="text-lg font-bold text-slate-900 dark:text-white">{title}</h2>
      <div className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed space-y-2">
        {children}
      </div>
    </section>
  );
}

function SubSection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="space-y-1.5">
      <h3 className="font-semibold text-slate-800 dark:text-slate-200 text-sm">{title}</h3>
      <div className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed">{children}</div>
    </div>
  );
}
